//! Approvals bootstrap for the **Safe wallet** (signature type 2) path.
//!
//! Deploys the Safe if needed, then grants the exchange contracts their
//! collateral (pUSD) and CTF approvals via relayer `SAFE` submissions.
//!
//! ERC-1271 deposit wallets (signature type 3) approve differently — batch
//! the `approve`/`setApprovalForAll` calldata through
//! [`RelayerClient::submit_deposit_wallet_batch`] instead.
#![allow(clippy::exhaustive_structs, reason = "Generated by sol! macro")]

use alloy::primitives::{Address, U256};
use alloy::providers::ProviderBuilder;
use alloy::signers::Signer;
use alloy::sol;
use alloy::sol_types::SolCall as _;

use crate::chain::{
    NEG_RISK_COLLATERAL_ADAPTER, POLYGON, contract_config, derive_safe_wallet, wallet_config,
};
use crate::error::Error;
use crate::relayer::RelayerClient;

sol! {
    #[sol(rpc)]
    interface IERC20 {
        function approve(address spender, uint256 value) external returns (bool);
        function allowance(address owner, address spender) external view returns (uint256);
    }

    #[sol(rpc)]
    interface IERC1155 {
        function setApprovalForAll(address operator, bool approved) external;
        function isApprovedForAll(address account, address operator) external view returns (bool);
    }

    #[sol(rpc)]
    interface ISafe {
        function nonce() external view returns (uint256);
    }
}

/// Ensure the signer's Safe wallet exists and holds the approvals negRisk
/// trading and position ops need.
///
/// Grants pUSD + CTF approvals for the V2 exchange, the legacy negRisk adapter,
/// and the pUSD collateral adapter that convert / merge / redeem now route
/// through. Idempotent: existing approvals are detected and skipped. A missing
/// Safe is deployed through the relayer first.
pub async fn ensure_approvals<S: Signer + Sync>(
    signer: &S,
    relayer: &RelayerClient,
    rpc_url: &str,
) -> Result<(), Error> {
    let eoa = signer.address();
    let safe = derive_safe_wallet(eoa, POLYGON)
        .ok_or_else(|| Error::InvalidData("failed to derive Safe wallet address".into()))?;

    tracing::info!(%eoa, %safe, "derived Safe wallet for approvals");

    let neg_risk_config = contract_config(POLYGON, true)
        .ok_or_else(|| Error::InvalidData("no neg risk contract config for Polygon".into()))?;

    let exchange_v2 = neg_risk_config
        .exchange_v2
        .ok_or_else(|| Error::InvalidData("no V2 exchange for Polygon".into()))?;

    let mut targets: Vec<(&str, Address)> = vec![("Neg Risk CTF Exchange V2", exchange_v2)];
    if let Some(adapter) = neg_risk_config.neg_risk_adapter {
        targets.push(("Neg Risk Adapter", adapter));
    }
    // The pUSD collateral adapter is the relayer-allowlisted entry point for
    // convert / merge / redeem / split since the pUSD migration; it must be a
    // CTF operator (and pUSD-approved, for split) to pull the wallet's tokens.
    targets.push(("Neg Risk Collateral Adapter", NEG_RISK_COLLATERAL_ADAPTER));

    let provider = ProviderBuilder::new()
        .connect(rpc_url)
        .await
        .map_err(|e| Error::InvalidData(format!("RPC connect failed: {e}")))?;

    let collateral = IERC20::new(neg_risk_config.collateral, &provider);
    let ctf = IERC1155::new(neg_risk_config.conditional_tokens, &provider);

    let safe_contract = ISafe::new(safe, &provider);
    let mut nonce: u64 = if let Ok(n) = safe_contract.nonce().call().await {
        let n = n.to::<u64>();
        tracing::info!(safe_nonce = n, "read Safe nonce");
        n
    } else {
        tracing::warn!("Safe not deployed at {safe}, deploying via relayer");
        let wallet_cfg = wallet_config(POLYGON)
            .ok_or_else(|| Error::InvalidData("no wallet config for Polygon".into()))?;
        relayer
            .deploy(signer, wallet_cfg.safe_factory, safe, POLYGON)
            .await?;
        tracing::info!("Safe deploy submitted, waiting for confirmation");
        tokio::time::sleep(std::time::Duration::from_secs(10)).await;
        0
    };

    for (name, target) in &targets {
        let allowance = collateral
            .allowance(safe, *target)
            .call()
            .await
            .map_err(|e| Error::InvalidData(format!("allowance check failed for {name}: {e}")))?;

        if allowance == U256::ZERO {
            tracing::info!(contract = name, "approving pUSD via relayer");
            let data = IERC20::approveCall {
                spender: *target,
                value: U256::MAX,
            }
            .abi_encode();

            let resp = relayer
                .submit(signer, safe, neg_risk_config.collateral, &data, nonce)
                .await?;
            tracing::info!(contract = name, tx_id = %resp.transaction_id, "pUSD approval submitted");
            nonce += 1;
        } else {
            tracing::info!(contract = name, "pUSD already approved");
        }

        let ctf_approved = ctf
            .isApprovedForAll(safe, *target)
            .call()
            .await
            .map_err(|e| {
                Error::InvalidData(format!("CTF approval check failed for {name}: {e}"))
            })?;

        if ctf_approved {
            tracing::info!(contract = name, "CTF already approved");
        } else {
            tracing::info!(contract = name, "approving CTF via relayer");
            let data = IERC1155::setApprovalForAllCall {
                operator: *target,
                approved: true,
            }
            .abi_encode();

            let resp = relayer
                .submit(
                    signer,
                    safe,
                    neg_risk_config.conditional_tokens,
                    &data,
                    nonce,
                )
                .await?;
            tracing::info!(contract = name, tx_id = %resp.transaction_id, "CTF approval submitted");
            nonce += 1;
        }
    }

    tracing::info!("all approvals verified");
    Ok(())
}
