//! negRisk position operations through the relayer: **convert**, **merge**,
//! **redeem**, and **split**, plus a planning engine that turns raw
//! balances into minimal relayer submissions.
//!
//! Layers, from pure to orchestrated:
//!
//! 1. **Calldata builders** ([`build_convert_calldata`] and friends) — pure
//!    ABI encoding against the negRisk adapter / CTF, always available.
//! 2. **Planner** ([`gas_chunks`], [`plan_calls`], [`ConvertTier`],
//!    [`EventPlan`]) — pure decomposition of balances into an ordered,
//!    gas-budgeted call list.
//! 3. **Engine** (`rpc` feature: [`plan_jobs`], [`process_jobs`],
//!    [`convert_worker`], the wrap helpers) — reads live balances over RPC,
//!    submits through [`RelayerClient`](crate::relayer::RelayerClient),
//!    retries wallet-busy, and wraps the freed USDC.e to pUSD.
//!
//! The negRisk math in one line each: **merge** burns YES+NO on one leg for
//! $1; **convert** burns NO across `k` legs of one event, minting YES on the
//! complement and freeing `(k−1)·amount`; **split** is merge's inverse
//! (collateral → YES+NO); **redeem** collects a resolved market's payout.
#![allow(clippy::exhaustive_structs, reason = "Generated by sol! macro")]

use std::time::Duration;

use alloy::primitives::{Address, B256, U256};
use alloy::sol;
use alloy::sol_types::SolCall as _;

use crate::chain::{COLLATERAL, COLLATERAL_ONRAMP, NEG_RISK_COLLATERAL_ADAPTER, USDC_E};
use crate::error::Error;
use crate::relayer::DepositWalletCall;

/// Max question ids per on-chain `convertPositions` index set.
///
/// The proven per-call width; wider tiers are truncated with compensating
/// post-merges (see [`ConvertTier`]). Distinct from the calls-per-submission
/// cap ([`ConvertDelays::max_calls_per_submission`]).
pub const MAX_LEGS_PER_CONVERT: usize = 20;

/// Tuning for the merge/convert cycle.
#[derive(Debug, Clone, Copy)]
pub struct ConvertDelays {
    /// Wait after a fill before starting the cycle (lets fills settle
    /// on-chain before the balance read).
    pub fill_to_convert: Duration,
    /// Wait for on-chain settlement after each relayer submission.
    pub settle: Duration,
    /// Max times to retry a submission while the relayer reports the wallet
    /// busy with a prior still-settling action.
    pub wallet_busy_max_retries: u32,
    /// Minimum leftover-NO (raw, 6-dp) on a *single* leg before it's worth a
    /// convert. Below this, a lone NO leg is left in place rather than
    /// spending gas to mint YES dust for 0 USDC. Multi-leg converts ignore
    /// this.
    pub single_leg_min_qty_raw: U256,
    /// Max `DepositWallet` calls packed into one relayer submission.
    pub max_calls_per_submission: usize,
    /// Gas budget per relayer submission. Converts on big events are heavy
    /// (measured live: 6.4–7.3M each on a 48-leg event); stacking six
    /// breached Polygon's 30M block limit and the relayer rejected the whole
    /// batch as "would revert". Chunks pack greedily under this budget; a
    /// lone over-budget call still submits by itself.
    pub max_gas_per_submission: u64,
    /// Fixed backoff after a failed cycle (anti-spin damp). The relayer's
    /// 429 `resets in` hint is deliberately ignored — it reports ~3600s
    /// while the quota actually frees in well under a minute.
    pub retry_backoff: Duration,
}

impl Default for ConvertDelays {
    fn default() -> Self {
        Self {
            fill_to_convert: Duration::from_secs(5),
            settle: Duration::from_secs(5),
            wallet_busy_max_retries: 10,
            single_leg_min_qty_raw: U256::from(100_000_u64),
            max_calls_per_submission: 20,
            max_gas_per_submission: 8_000_000,
            retry_backoff: Duration::from_secs(45),
        }
    }
}

// Encode-only interfaces (no provider coupling): available without the `rpc`
// feature. Selectors derive from the signatures alone.
sol! {
    interface INegRiskAdapterOps {
        /// The one op the collateral adapter still takes in its legacy form —
        /// same calldata as the old `NegRiskAdapter.convertPositions`. Merge /
        /// redeem / split use the CTF-mirror overloads ([`ICtfOps`]) instead;
        /// their legacy 2-arg forms exist on the adapter but REVERT.
        function convertPositions(
            bytes32 marketId,
            uint256 indexSet,
            uint256 amount
        ) external;
    }

    interface ICtfOps {
        function splitPosition(
            address collateralToken,
            bytes32 parentCollectionId,
            bytes32 conditionId,
            uint256[] partition,
            uint256 amount
        ) external;

        function mergePositions(
            address collateralToken,
            bytes32 parentCollectionId,
            bytes32 conditionId,
            uint256[] partition,
            uint256 amount
        ) external;

        function redeemPositions(
            address collateralToken,
            bytes32 parentCollectionId,
            bytes32 conditionId,
            uint256[] indexSets
        ) external;
    }

    interface ICollateralOnrampOps {
        function wrap(
            address asset,
            address to,
            uint256 amount
        ) external;
    }

    interface IErc20Ops {
        function approve(address spender, uint256 value) external returns (bool);
    }
}

#[cfg(feature = "rpc")]
mod rpc_ifaces {
    #![allow(clippy::exhaustive_structs, reason = "Generated by sol! macro")]
    use alloy::sol;

    sol! {
        #[sol(rpc)]
        interface IERC20 {
            function allowance(address owner, address spender) external view returns (uint256);
            function balanceOf(address account) external view returns (uint256);
        }

        #[sol(rpc)]
        interface IERC1155 {
            function balanceOfBatch(address[] accounts, uint256[] ids) external view returns (uint256[]);
        }
    }
}

/// One market leg's on-chain identifiers, parsed and ready for planning.
#[derive(Debug, Clone)]
pub struct ConvertLeg {
    pub question_id: B256,
    pub condition_id: Option<B256>,
    pub yes_token_id: Option<U256>,
    pub no_token_id: U256,
}

/// One event's convert work: its legs plus caller-side bookkeeping carried
/// through the worker channel.
#[derive(Debug)]
pub struct ConvertJob {
    pub slug: String,
    pub legs: Vec<ConvertLeg>,
    /// Advisory amount the caller expected to free (the engine plans from
    /// live balances; this rides along for the caller's accounting).
    pub amount_raw: U256,
    /// Prior failed attempts, echoed back on [`ConvertResult`] so the caller
    /// can apply a retry cap across the channel round-trip.
    pub attempts: u32,
    /// When the job was queued — the anchor for the worker's fill-settle
    /// wait, so a job that aged in the channel isn't re-delayed in full.
    pub queued_at: std::time::Instant,
}

/// One market's identifiers as string-typed API data (the shapes Gamma and
/// the Data API deliver them in).
#[derive(Debug, Clone, Copy)]
pub struct MarketIds<'a> {
    /// Hex, with or without `0x`.
    pub question_id: Option<&'a str>,
    /// Hex, with or without `0x`.
    pub condition_id: Option<&'a str>,
    /// Decimal token id.
    pub yes_token_id: Option<&'a str>,
    /// Decimal token id.
    pub no_token_id: &'a str,
}

/// Parse [`ConvertLeg`]s out of string-typed market ids.
///
/// Skips any market missing a parseable `question_id` or `no_token_id` —
/// unparseable legs are silently unplannable rather than fatal.
#[must_use]
pub fn convert_legs<'a>(markets: impl IntoIterator<Item = MarketIds<'a>>) -> Vec<ConvertLeg> {
    fn parse_b256(raw: &str) -> Option<B256> {
        raw.strip_prefix("0x").unwrap_or(raw).parse().ok()
    }

    markets
        .into_iter()
        .filter_map(|m| {
            let question_id = parse_b256(m.question_id?)?;
            let no_token_id = m.no_token_id.parse().ok()?;
            let yes_token_id = m.yes_token_id.and_then(|y| y.parse().ok());
            let condition_id = m.condition_id.and_then(parse_b256);
            Some(ConvertLeg {
                question_id,
                condition_id,
                yes_token_id,
                no_token_id,
            })
        })
        .collect()
}

/// Derive the shared negRisk event `marketId` from any question ID.
///
/// The last byte encodes the per-question index; zeroing it yields the
/// shared event identifier.
#[must_use]
pub fn market_id_from_question_id(question_id: &B256) -> B256 {
    let mut bytes = question_id.0;
    bytes[31] = 0;
    B256::from(bytes)
}

/// Compute the index-set bitmap for a set of question IDs.
///
/// Each question ID's last byte is its position index within the event.
#[must_use]
pub fn index_set(question_ids: &[B256]) -> U256 {
    let mut bits = U256::ZERO;
    for qid in question_ids {
        let idx = qid.0[31];
        bits |= U256::from(1_u64) << idx;
    }
    bits
}

/// Calldata for `NegRiskAdapter.convertPositions`: burn `amount` NO on every
/// leg in `question_ids`, minting `amount` YES on the event's complement.
pub fn build_convert_calldata(question_ids: &[B256], amount: U256) -> Result<Vec<u8>, Error> {
    if question_ids.is_empty() {
        return Err(Error::InvalidData(
            "convert requires at least one question_id".into(),
        ));
    }
    let market_id = market_id_from_question_id(&question_ids[0]);
    let idx_set = index_set(question_ids);

    Ok(INegRiskAdapterOps::convertPositionsCall {
        marketId: market_id,
        indexSet: idx_set,
        amount,
    }
    .abi_encode())
}

/// Calldata to merge `amount` YES+NO on `condition_id` back into `amount`
/// collateral, through the pUSD [`NEG_RISK_COLLATERAL_ADAPTER`].
///
/// The adapter mirrors the CTF ABI, so this is the CTF-mirror
/// `mergePositions(collateralToken, parentCollectionId, conditionId, partition, amount)`
/// with pUSD collateral, a zero parent collection, and the binary `[1, 2]`
/// partition — verified against a live UI merge (tx `0xe92073a6…`). The
/// legacy-style `mergePositions(bytes32,uint256)` overload the old adapter took
/// still exists in this adapter's bytecode but REVERTS.
#[must_use]
pub fn build_merge_calldata(condition_id: &B256, amount: U256) -> Vec<u8> {
    build_merge_calldata_ctf(COLLATERAL, condition_id, amount)
}

/// Calldata to split `amount` collateral into `amount` YES+NO on
/// `condition_id` (merge's inverse).
///
/// Goes through the pUSD [`NEG_RISK_COLLATERAL_ADAPTER`] as the CTF-mirror
/// `splitPosition(collateralToken, parentCollectionId, conditionId, partition, amount)`.
///
/// ⚠ The least-exercised call in this crate, and the only one **not** verified
/// against a live on-chain tx. The heavily exercised merge takes the exact
/// symmetric CTF-mirror form through this same adapter, so this is the
/// consistent shape — but split a dust amount first before trusting it with
/// size. Splitting also requires the adapter to be approved to pull the
/// wallet's pUSD collateral.
#[must_use]
pub fn build_split_calldata(condition_id: &B256, amount: U256) -> Vec<u8> {
    build_split_calldata_ctf(COLLATERAL, condition_id, amount)
}

/// Calldata for the plain CTF `splitPosition` (non-negRisk markets):
/// `parentCollectionId` zero and the binary partition `[1, 2]`.
#[must_use]
pub fn build_split_calldata_ctf(collateral: Address, condition_id: &B256, amount: U256) -> Vec<u8> {
    ICtfOps::splitPositionCall {
        collateralToken: collateral,
        parentCollectionId: B256::ZERO,
        conditionId: *condition_id,
        partition: vec![U256::from(1_u64), U256::from(2_u64)],
        amount,
    }
    .abi_encode()
}

/// Calldata for the plain CTF `mergePositions` (non-negRisk markets) — the
/// symmetric inverse of [`build_split_calldata_ctf`].
#[must_use]
pub fn build_merge_calldata_ctf(collateral: Address, condition_id: &B256, amount: U256) -> Vec<u8> {
    ICtfOps::mergePositionsCall {
        collateralToken: collateral,
        parentCollectionId: B256::ZERO,
        conditionId: *condition_id,
        partition: vec![U256::from(1_u64), U256::from(2_u64)],
        amount,
    }
    .abi_encode()
}

/// Calldata to redeem a resolved negRisk condition through the pUSD
/// [`NEG_RISK_COLLATERAL_ADAPTER`].
///
/// The adapter mirrors the CTF ABI, so this is the CTF-mirror
/// `redeemPositions(collateralToken, parentCollectionId, conditionId, indexSets)`
/// with pUSD collateral and a zero parent collection — verified against live
/// on-chain redeems (tx `0x2252f36d…` used `[1, 2]`, `0x7bb402a9…` used `[1]`).
/// Unlike the legacy `redeemPositions(bytes32,uint256[])` (which took explicit
/// `[yes, no]` amounts and REVERTS on this adapter), the CTF-mirror form takes
/// **index sets** and redeems the caller's *full* balance of each: `yes_amount`
/// / `no_amount` here only decide **which** sides to include (`> 0`), not how
/// much — `YES = index set 1` (outcome slot 0), `NO = index set 2` (slot 1).
/// Only meaningful once the condition is resolved (an unresolved redeem reverts
/// in the CTF); the caller gates on that and filters both-zero legs.
#[must_use]
pub fn build_redeem_calldata(condition_id: &B256, yes_amount: U256, no_amount: U256) -> Vec<u8> {
    let mut index_sets = Vec::with_capacity(2);
    if yes_amount > U256::ZERO {
        index_sets.push(U256::from(1_u64));
    }
    if no_amount > U256::ZERO {
        index_sets.push(U256::from(2_u64));
    }
    build_redeem_calldata_ctf(COLLATERAL, condition_id, &index_sets)
}

/// Calldata for the plain CTF `redeemPositions` (binary markets):
/// `parentCollectionId` zero and the outcome `index_sets` to redeem (`[1, 2]`
/// covers both slots of a binary condition).
///
/// Unlike [`build_redeem_calldata`], the CTF redeems the caller's *full*
/// balance of the given index sets (no per-token amounts) and pays out in
/// `collateral` — so pass the collateral token the condition was prepared
/// with. Only meaningful once the condition is resolved.
#[must_use]
pub fn build_redeem_calldata_ctf(
    collateral: Address,
    condition_id: &B256,
    index_sets: &[U256],
) -> Vec<u8> {
    ICtfOps::redeemPositionsCall {
        collateralToken: collateral,
        parentCollectionId: B256::ZERO,
        conditionId: *condition_id,
        indexSets: index_sets.to_vec(),
    }
    .abi_encode()
}

/// `DepositWallet` calls to redeem resolved negRisk positions, one per
/// condition.
///
/// `redeems` is `(condition_id, yes_amount, no_amount)`; every call targets
/// the shared [`NEG_RISK_COLLATERAL_ADAPTER`]. The caller filters out legs with
/// both amounts zero and gates on resolution.
#[must_use]
pub fn redeem_calls(redeems: &[(B256, U256, U256)]) -> Vec<DepositWalletCall> {
    redeems
        .iter()
        .map(|(cid, yes, no)| DepositWalletCall {
            target: NEG_RISK_COLLATERAL_ADAPTER,
            data: build_redeem_calldata(cid, *yes, *no),
        })
        .collect()
}

/// `DepositWallet` calls to merge YES+NO pairs, one per condition.
/// `merges` is `(condition_id, amount)`.
#[must_use]
pub fn merge_calls(merges: &[(B256, U256)]) -> Vec<DepositWalletCall> {
    merges
        .iter()
        .map(|(cid, amount)| DepositWalletCall {
            target: NEG_RISK_COLLATERAL_ADAPTER,
            data: build_merge_calldata(cid, *amount),
        })
        .collect()
}

/// `DepositWallet` calls to split collateral into YES+NO on negRisk
/// conditions, one per condition.
///
/// `splits` is `(condition_id, amount)`. Mirrors [`merge_calls`]; see
/// [`build_split_calldata`] for the net-new caveat.
#[must_use]
pub fn split_calls(splits: &[(B256, U256)]) -> Vec<DepositWalletCall> {
    splits
        .iter()
        .map(|(cid, amount)| DepositWalletCall {
            target: NEG_RISK_COLLATERAL_ADAPTER,
            data: build_split_calldata(cid, *amount),
        })
        .collect()
}

/// Render a raw 6-dp USDC amount as a decimal string (e.g. `12.345678`).
#[must_use]
pub fn fmt_usdc(raw: U256) -> String {
    let v: u128 = raw.try_into().unwrap_or(u128::MAX);
    format!("{}.{:06}", v / 1_000_000, v % 1_000_000)
}

/// One leg still holding NO after its YES+NO merge is netted out — the unit
/// the tier planner works over.
#[derive(Debug, Clone, PartialEq, Eq)]
struct NoHolding {
    question_id: B256,
    condition_id: Option<B256>,
    /// NO left after `min(yes, no)` is merged away (or merely offset, when
    /// the leg has no condition id to merge through).
    remaining_no: U256,
}

/// One convert call: burn `amount` NO across `question_ids`.
///
/// `post_merges` are the compensating merges for members truncated past the
/// per-call leg cap — the convert mints `amount` YES on every leg outside
/// its index set, so merging that YES against a truncated member's
/// still-held NO frees the same `$amount` the untruncated convert would
/// have. They MUST execute after this tier's convert (they consume the YES
/// it mints).
#[derive(Debug, PartialEq, Eq)]
pub struct ConvertTier {
    pub question_ids: Vec<B256>,
    pub amount: U256,
    pub post_merges: Vec<(B256, U256)>,
}

/// Deterministic full merge/convert plan for one event, computed from a
/// single balance snapshot.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct EventPlan {
    /// Pre-convert YES+NO merges, `(condition_id, amount)`.
    pub merges: Vec<(B256, U256)>,
    /// Convert tiers in execution order.
    pub tiers: Vec<ConvertTier>,
    /// Exact USDC.e (raw, 6-dp) the plan frees: each merge frees its amount,
    /// a convert across `k` legs frees `(k−1)·amount`.
    pub proceeds: U256,
    /// The event's total leg count — drives the per-convert gas estimate
    /// (the adapter's convert cost scales with the whole event, not the
    /// index set).
    pub n_legs: usize,
}

/// Static merge gas estimate for chunk packing, measured live.
///
/// A probe on a 48-leg event measured merge ≈ 330k and converts 6.4–7.3M
/// (≈ ~140k per event leg — the adapter splits collateral across every
/// complement leg and merges a full set across all of the event's
/// conditions, so cost scales with the whole event, not the index set).
/// Weights carry ~25% margin: overestimating costs an extra submission;
/// underestimating gets the whole batch rejected as "would revert".
pub const MERGE_GAS: u64 = 400_000;

/// Gas estimate for one convert on an event with `n_event_legs` legs.
#[must_use]
pub fn convert_gas(n_event_legs: usize) -> u64 {
    let n = u64::try_from(n_event_legs).unwrap_or(u64::MAX);
    700_000_u64.saturating_add(175_000_u64.saturating_mul(n))
}

/// One planned `DepositWallet` call plus its gas estimate for chunk packing.
#[derive(Debug)]
pub struct PlannedCall {
    pub call: DepositWalletCall,
    pub gas: u64,
}

/// Greedy contiguous chunking under both a call-count cap and a gas budget.
///
/// Returns index ranges into the planned-call slice; concatenated they cover
/// it exactly, preserving order (which is load-bearing — see
/// [`plan_calls`]). A single call over the gas budget still gets a chunk of
/// its own: calls are atomic, and the relayer historically accepted lone
/// big-event converts.
#[must_use]
pub fn gas_chunks(
    planned: &[PlannedCall],
    max_calls: usize,
    max_gas: u64,
) -> Vec<std::ops::Range<usize>> {
    let max_calls = max_calls.max(1);
    let mut ranges = Vec::new();
    let mut start = 0_usize;
    let mut gas = 0_u64;
    for (i, p) in planned.iter().enumerate() {
        let count = i - start;
        if count > 0 && (count >= max_calls || gas.saturating_add(p.gas) > max_gas) {
            ranges.push(start..i);
            start = i;
            gas = 0;
        }
        gas = gas.saturating_add(p.gas);
    }
    if start < planned.len() {
        ranges.push(start..planned.len());
    }
    ranges
}

/// Pre-submission USDC.e snapshot driving the folded wrap.
#[derive(Debug, Clone, Copy)]
pub struct WrapSnapshot {
    pub balance: U256,
    pub allowance: U256,
}

/// Classify per-leg `(no, yes)` balances into pre-convert merges and the
/// remaining-NO holdings the tier planner works over.
///
/// A leg holding both sides merges `min(yes, no)` when it has a condition
/// id; either way the NO left over is `no − min(yes, no)` — without a
/// condition id the YES can't merge but still offsets that much NO (it is
/// never converted).
fn classify_event(
    legs: &[ConvertLeg],
    pairs: &[(U256, U256)],
) -> (Vec<(B256, U256)>, Vec<NoHolding>) {
    let mut merges = Vec::new();
    let mut holdings = Vec::new();

    for (leg, &(no_bal, yes_bal)) in legs.iter().zip(pairs) {
        if yes_bal > U256::ZERO
            && no_bal > U256::ZERO
            && let Some(cid) = leg.condition_id
        {
            merges.push((cid, yes_bal.min(no_bal)));
        }

        let remaining_no = no_bal.saturating_sub(yes_bal.min(no_bal));
        if remaining_no > U256::ZERO {
            holdings.push(NoHolding {
                question_id: leg.question_id,
                condition_id: leg.condition_id,
                remaining_no,
            });
        }
    }

    (merges, holdings)
}

/// Decompose remaining-NO holdings into convert tiers.
///
/// Distinct holding sizes `L1 < L2 < …` define the tiers: tier 1 converts
/// `L1` across every NO-holding leg, tier 2 converts `L2 − L1` across the
/// legs holding more than `L1`, and so on — the fixpoint a
/// read→convert→re-read loop converges to, but computable from one balance
/// snapshot because conditional-token math is deterministic.
///
/// A tier wider than `max_legs` is truncated to its first `max_legs` members
/// (input order): the convert then mints `amount` YES on each truncated-out
/// member, so cid-bearing ones get a compensating post-merge freeing the
/// same `$amount` the untruncated convert would have.
///
/// A lone-member tier is necessarily the last (membership shrinks as levels
/// rise); converting it frees 0 USDC, so it is kept for position hygiene
/// only when `amount ≥ single_leg_min_qty_raw`.
fn plan_tiers(
    holdings: &[NoHolding],
    single_leg_min_qty_raw: U256,
    max_legs: usize,
) -> Vec<ConvertTier> {
    let mut levels: Vec<U256> = holdings.iter().map(|h| h.remaining_no).collect();
    levels.sort_unstable();
    levels.dedup();

    let mut tiers = Vec::with_capacity(levels.len());
    let mut prev = U256::ZERO;
    for level in levels {
        let amount = level - prev;
        prev = level;
        let members: Vec<&NoHolding> = holdings
            .iter()
            .filter(|h| h.remaining_no >= level)
            .collect();
        if members.len() == 1 && amount < single_leg_min_qty_raw {
            break;
        }
        let question_ids = members
            .iter()
            .take(max_legs)
            .map(|h| h.question_id)
            .collect();
        let post_merges = members
            .iter()
            .skip(max_legs)
            .filter_map(|h| h.condition_id.map(|cid| (cid, amount)))
            .collect();
        tiers.push(ConvertTier {
            question_ids,
            amount,
            post_merges,
        });
    }
    tiers
}

/// Assemble an event's plan and compute the exact USDC.e it frees. `n_legs`
/// is the event's total leg count (drives the per-convert gas estimate).
fn plan_event(merges: Vec<(B256, U256)>, tiers: Vec<ConvertTier>, n_legs: usize) -> EventPlan {
    let mut proceeds = merges.iter().fold(U256::ZERO, |acc, &(_, a)| acc + a);
    for tier in &tiers {
        proceeds += U256::from(tier.question_ids.len().saturating_sub(1)) * tier.amount;
        proceeds = tier
            .post_merges
            .iter()
            .fold(proceeds, |acc, &(_, a)| acc + a);
    }
    EventPlan {
        merges,
        tiers,
        proceeds,
        n_legs,
    }
}

/// Compute an event's plan from a balance snapshot: per-leg `(no, yes)`
/// balance pairs in leg order (the pure entry into the planner for callers
/// bringing their own balance source).
#[must_use]
pub fn plan_event_from_balances(
    legs: &[ConvertLeg],
    pairs: &[(U256, U256)],
    single_leg_min_qty_raw: U256,
) -> EventPlan {
    let (merges, holdings) = classify_event(legs, pairs);
    let tiers = plan_tiers(&holdings, single_leg_min_qty_raw, MAX_LEGS_PER_CONVERT);
    plan_event(merges, tiers, legs.len())
}

/// Flatten per-event plans into one ordered, gas-weighted merge/convert call
/// list.
///
/// Order is load-bearing: each event's merges precede its converts (tier
/// amounts assume post-merge balances), and each tier's post-merges directly
/// follow that tier's convert (they consume the YES it mints). Calls execute
/// in order inside a relayer submission, and chunked submissions are
/// serialized, so the order survives chunking.
///
/// Every call here is also individually valid against the *pre-batch*
/// balance snapshot. Two batch shapes are known to be rejected by the
/// relayer's pre-submission simulation ("batch would revert"), both observed
/// live, and both avoided here:
/// - an in-batch wrap sized to include the batch's proceeds (the wrap
///   instead goes out as its own balance-read-sized submission after the
///   batch lands);
/// - a batch whose summed gas exceeds what one transaction can execute
///   (hence the gas weights here and the budget chunking in [`gas_chunks`]).
pub fn plan_calls(plans: &[EventPlan]) -> Result<Vec<PlannedCall>, Error> {
    let mut calls = Vec::new();

    for plan in plans {
        for call in merge_calls(&plan.merges) {
            calls.push(PlannedCall {
                call,
                gas: MERGE_GAS,
            });
        }
        for tier in &plan.tiers {
            calls.push(PlannedCall {
                call: DepositWalletCall {
                    target: NEG_RISK_COLLATERAL_ADAPTER,
                    data: build_convert_calldata(&tier.question_ids, tier.amount)?,
                },
                gas: convert_gas(plan.n_legs),
            });
            for call in merge_calls(&tier.post_merges) {
                calls.push(PlannedCall {
                    call,
                    gas: MERGE_GAS,
                });
            }
        }
    }

    Ok(calls)
}

/// Calldata for wrapping `amount` USDC.e into pUSD via the onramp, with an
/// unlimited-approve call prepended when `include_approve`.
#[must_use]
pub fn wrap_calls(wallet: Address, amount: U256, include_approve: bool) -> Vec<DepositWalletCall> {
    let mut calls = Vec::with_capacity(2);
    if include_approve {
        calls.push(DepositWalletCall {
            target: USDC_E,
            data: IErc20Ops::approveCall {
                spender: COLLATERAL_ONRAMP,
                value: U256::MAX,
            }
            .abi_encode(),
        });
    }
    calls.push(DepositWalletCall {
        target: COLLATERAL_ONRAMP,
        data: ICollateralOnrampOps::wrapCall {
            asset: USDC_E,
            to: wallet,
            amount,
        }
        .abi_encode(),
    });
    calls
}

// ---------------------------------------------------------------------------
// The engine: live balance reads + relayer orchestration (`rpc` feature)
// ---------------------------------------------------------------------------

#[cfg(feature = "rpc")]
pub use engine::{
    ConvertResult, convert_worker, plan_jobs, process_convert, process_job, process_jobs,
    process_merge, submit_and_settle_with_busy_retry, wrap_usdc_e, wrap_with_busy_retry,
};

#[cfg(feature = "rpc")]
mod engine {
    use std::collections::HashSet;
    use std::time::{Duration, Instant};

    use alloy::primitives::{Address, B256, U256};
    use alloy::providers::ProviderBuilder;
    use alloy::signers::Signer;
    use tokio::sync::mpsc;

    use super::rpc_ifaces::{IERC20, IERC1155};
    use super::{
        ConvertDelays, ConvertJob, ConvertLeg, WrapSnapshot, build_convert_calldata, fmt_usdc,
        gas_chunks, plan_calls, plan_event_from_balances, wrap_calls,
    };
    use crate::chain::{COLLATERAL_ONRAMP, CTF, NEG_RISK_COLLATERAL_ADAPTER, POLYGON, USDC_E};
    use crate::error::Error;
    use crate::relayer::{DepositWalletCall, RelayerClient};

    /// Outcome of one convert job, echoed per consumed job.
    #[derive(Debug)]
    pub struct ConvertResult {
        pub slug: String,
        pub amount_raw: U256,
        pub n_legs: usize,
        pub success: bool,
        /// Set when the failure was relayer quota exhaustion — retry these
        /// on a fixed backoff (they self-terminate once the quota frees);
        /// cap retries on non-quota failures.
        pub quota_blocked: bool,
        /// Echo of the job's `attempts` for the caller's retry cap.
        pub attempts: u32,
        pub detail: String,
    }

    /// Remaining fill-settle wait for the youngest job in the batch:
    /// `fill_delay` measured from each job's `queued_at`, so a job that
    /// already aged in the channel doesn't wait the full delay over again.
    fn fill_residual(batch: &[ConvertJob], now: Instant, fill_delay: Duration) -> Duration {
        batch
            .iter()
            .map(|j| fill_delay.saturating_sub(now.saturating_duration_since(j.queued_at)))
            .max()
            .unwrap_or(Duration::ZERO)
    }

    /// First occurrence per slug wins (same slug ⇒ same legs); input order
    /// kept.
    fn dedup_by_slug(batch: &[ConvertJob]) -> Vec<&ConvertJob> {
        let mut seen = HashSet::new();
        batch
            .iter()
            .filter(|j| seen.insert(j.slug.as_str()))
            .collect()
    }

    /// Background merge/convert worker: drains queued jobs into one
    /// coalesced cycle per pass.
    ///
    /// Each pass waits out the youngest job's fill-settle delay, drains
    /// whatever else queued meanwhile (a burst of fills becomes one shared
    /// cycle instead of N serialized ones), dedups by slug, and runs
    /// [`process_jobs`] over the distinct events. Exactly one
    /// [`ConvertResult`] is sent per *consumed* job — duplicates included —
    /// so callers that count queued jobs and decrement per result never
    /// stall on a missing result.
    pub async fn convert_worker<S: Signer + Sync>(
        mut rx: mpsc::Receiver<ConvertJob>,
        signer: S,
        relayer: RelayerClient,
        rpc_url: String,
        proxy_wallet: Address,
        result_tx: mpsc::UnboundedSender<ConvertResult>,
        delays: ConvertDelays,
    ) {
        tracing::info!(%proxy_wallet, "convert worker started");

        while let Some(first) = rx.recv().await {
            let mut batch = vec![first];
            tokio::time::sleep(fill_residual(
                &batch,
                Instant::now(),
                delays.fill_to_convert,
            ))
            .await;
            // Single drain: jobs that arrived during the wait join this
            // cycle; later arrivals start the next pass immediately after
            // this one resolves.
            while let Ok(job) = rx.try_recv() {
                batch.push(job);
            }
            // Just-drained jobs may be younger than the fill delay; top up so
            // every job's fills have settled on-chain before the balance read.
            tokio::time::sleep(fill_residual(
                &batch,
                Instant::now(),
                delays.fill_to_convert,
            ))
            .await;

            let outcome = {
                let uniques = dedup_by_slug(&batch);
                tracing::info!(
                    jobs = batch.len(),
                    events = uniques.len(),
                    "convert cycle starting"
                );
                process_jobs(&uniques, &signer, &relayer, &rpc_url, proxy_wallet, delays).await
            };

            match outcome {
                Ok(detail) => {
                    tracing::info!(%detail, "convert cycle complete");
                    for job in batch {
                        let _ = result_tx.send(ConvertResult {
                            slug: job.slug,
                            amount_raw: job.amount_raw,
                            n_legs: job.legs.len(),
                            success: true,
                            quota_blocked: false,
                            attempts: job.attempts,
                            detail: detail.clone(),
                        });
                    }
                }
                Err(Error::RelayerQuotaExhausted { resets_in_secs }) => {
                    // The relayer's hint is unreliable — logged for forensics
                    // only; the caller retries on the fixed backoff, and this
                    // sleep is an anti-spin damp.
                    tracing::warn!(resets_in_secs, "relayer quota exhausted");
                    for job in batch {
                        let _ = result_tx.send(ConvertResult {
                            slug: job.slug,
                            amount_raw: job.amount_raw,
                            n_legs: job.legs.len(),
                            success: false,
                            quota_blocked: true,
                            attempts: job.attempts,
                            detail: "quota exhausted".to_string(),
                        });
                    }
                    tokio::time::sleep(delays.retry_backoff).await;
                }
                Err(e) => {
                    tracing::error!(error = %e, "convert cycle failed");
                    let detail = e.to_string();
                    for job in batch {
                        let _ = result_tx.send(ConvertResult {
                            slug: job.slug,
                            amount_raw: job.amount_raw,
                            n_legs: job.legs.len(),
                            success: false,
                            quota_blocked: false,
                            attempts: job.attempts,
                            detail: detail.clone(),
                        });
                    }
                    tokio::time::sleep(delays.retry_backoff).await;
                }
            }
        }
    }

    async fn submit_and_settle<S: Signer + Sync>(
        signer: &S,
        relayer: &RelayerClient,
        wallet: Address,
        calls: &[DepositWalletCall],
        label: &str,
        settle: Duration,
    ) -> Result<String, Error> {
        let resp = relayer
            .submit_deposit_wallet_batch(signer, wallet, POLYGON, calls)
            .await?;
        tracing::info!(tx_id = %resp.transaction_id, "{label} submitted, waiting for settlement");
        tokio::time::sleep(settle).await;
        Ok(resp.transaction_id)
    }

    /// Submit a relayer batch and wait for settlement, retrying while the
    /// relayer reports the wallet busy.
    ///
    /// A "wallet busy: active action exists" rejection means a prior action
    /// for this wallet is still settling and *nothing was submitted*, so
    /// retrying is safe — there is no double-submission risk. The condition
    /// clears once the prior action lands, so wait `settle` and try again,
    /// up to `max_retries` times. Any non-busy error returns immediately.
    pub async fn submit_and_settle_with_busy_retry<S: Signer + Sync>(
        signer: &S,
        relayer: &RelayerClient,
        wallet: Address,
        calls: &[DepositWalletCall],
        label: &str,
        settle: Duration,
        max_retries: u32,
    ) -> Result<String, Error> {
        let mut attempt = 0;
        loop {
            match submit_and_settle(signer, relayer, wallet, calls, label, settle).await {
                Ok(tx_id) => return Ok(tx_id),
                Err(e) if e.is_wallet_busy() && attempt < max_retries => {
                    attempt += 1;
                    tracing::warn!(
                        %label,
                        attempt,
                        max_retries,
                        wait_secs = settle.as_secs(),
                        "submit deferred: wallet busy, waiting then retrying"
                    );
                    tokio::time::sleep(settle).await;
                }
                Err(e) => return Err(e),
            }
        }
    }

    /// Flatten the legs' token ids into one `balanceOfBatch` query: per leg,
    /// the NO token id, then the YES token id when known.
    /// [`unpack_balances`] walks the same layout back out.
    fn batch_token_ids(legs: &[ConvertLeg]) -> Vec<U256> {
        let mut ids = Vec::with_capacity(legs.len() * 2);
        for leg in legs {
            ids.push(leg.no_token_id);
            if let Some(yid) = leg.yes_token_id {
                ids.push(yid);
            }
        }
        ids
    }

    /// Number of token ids [`batch_token_ids`] emits for these legs.
    fn token_count(legs: &[ConvertLeg]) -> usize {
        legs.iter()
            .map(|l| 1 + usize::from(l.yes_token_id.is_some()))
            .sum()
    }

    /// Inverse of [`batch_token_ids`]: split the flat balance array back
    /// into per-leg `(no, yes)` pairs. Legs without a YES token id get a
    /// zero YES balance. Errors when the array length doesn't match the
    /// queried layout.
    fn unpack_balances(legs: &[ConvertLeg], balances: &[U256]) -> Result<Vec<(U256, U256)>, Error> {
        fn truncated() -> Error {
            Error::InvalidData("balanceOfBatch returned fewer balances than queried".into())
        }

        let mut cursor = balances.iter().copied();
        let mut pairs = Vec::with_capacity(legs.len());
        for leg in legs {
            let no_bal = cursor.next().ok_or_else(truncated)?;
            let yes_bal = if leg.yes_token_id.is_some() {
                cursor.next().ok_or_else(truncated)?
            } else {
                U256::ZERO
            };
            pairs.push((no_bal, yes_bal));
        }
        if cursor.next().is_some() {
            return Err(Error::InvalidData(
                "balanceOfBatch returned more balances than queried".into(),
            ));
        }
        Ok(pairs)
    }

    /// Split one combined multi-job `balanceOfBatch` result back into
    /// per-job, per-leg `(no, yes)` pairs (jobs were concatenated in order).
    fn unpack_multi(
        jobs: &[&ConvertJob],
        balances: &[U256],
    ) -> Result<Vec<Vec<(U256, U256)>>, Error> {
        let mut out = Vec::with_capacity(jobs.len());
        let mut offset = 0_usize;
        for job in jobs {
            let n = token_count(&job.legs);
            let slice = balances.get(offset..offset + n).ok_or_else(|| {
                Error::InvalidData("balanceOfBatch returned fewer balances than queried".into())
            })?;
            out.push(unpack_balances(&job.legs, slice)?);
            offset += n;
        }
        if offset != balances.len() {
            return Err(Error::InvalidData(
                "balanceOfBatch returned more balances than queried".into(),
            ));
        }
        Ok(out)
    }

    /// Read every job's CTF balances in a single `balanceOfBatch` `eth_call`
    /// (same-block consistent across all events, one billed RPC call total).
    ///
    /// Propagates RPC errors instead of masking them as zero balances: an
    /// ERC1155 read returns 0 for an unheld token, so a masked *failed read*
    /// would silently skip converting a real position and look like "nothing
    /// to do".
    async fn read_balances_multi(
        jobs: &[&ConvertJob],
        rpc_url: &str,
        wallet: Address,
    ) -> Result<Vec<Vec<(U256, U256)>>, Error> {
        let mut ids: Vec<U256> =
            Vec::with_capacity(jobs.iter().map(|j| token_count(&j.legs)).sum());
        for job in jobs {
            ids.extend(batch_token_ids(&job.legs));
        }
        if ids.is_empty() {
            return Ok(jobs.iter().map(|_| Vec::new()).collect());
        }

        let provider = ProviderBuilder::new()
            .connect(rpc_url)
            .await
            .map_err(|e| Error::InvalidData(format!("RPC connect failed: {e}")))?;
        let ctf = IERC1155::new(CTF, &provider);

        let n = ids.len();
        let balances = ctf
            .balanceOfBatch(vec![wallet; n], ids)
            .call()
            .await
            .map_err(|e| Error::InvalidData(format!("balanceOfBatch failed: {e}")))?;

        unpack_multi(jobs, &balances)
    }

    /// Read the wallet's USDC.e balance and onramp allowance — the folded
    /// wrap's inputs.
    async fn read_wrap_snapshot(rpc_url: &str, wallet: Address) -> Result<WrapSnapshot, Error> {
        let provider = ProviderBuilder::new()
            .connect(rpc_url)
            .await
            .map_err(|e| Error::InvalidData(format!("RPC connect failed: {e}")))?;
        let usdc = IERC20::new(USDC_E, &provider);

        let balance = usdc
            .balanceOf(wallet)
            .call()
            .await
            .map_err(|e| Error::InvalidData(format!("USDC balance read failed: {e}")))?;
        let allowance = usdc
            .allowance(wallet, COLLATERAL_ONRAMP)
            .call()
            .await
            .map_err(|e| Error::InvalidData(format!("USDC allowance read failed: {e}")))?;

        Ok(WrapSnapshot { balance, allowance })
    }

    /// Read live balances and produce per-job [`super::EventPlan`]s plus the
    /// wrap snapshot — submits nothing. Drives [`process_jobs`] and
    /// read-only planning reports.
    pub async fn plan_jobs(
        jobs: &[&ConvertJob],
        rpc_url: &str,
        wallet: Address,
        single_leg_min_qty_raw: U256,
    ) -> Result<(Vec<super::EventPlan>, WrapSnapshot), Error> {
        let (balances, snapshot) = tokio::join!(
            read_balances_multi(jobs, rpc_url, wallet),
            read_wrap_snapshot(rpc_url, wallet)
        );
        let (balances, snapshot) = (balances?, snapshot?);

        let plans = jobs
            .iter()
            .zip(&balances)
            .map(|(job, pairs)| plan_event_from_balances(&job.legs, pairs, single_leg_min_qty_raw))
            .collect();

        Ok((plans, snapshot))
    }

    /// Run the full merge→convert→wrap cycle for one or more events in as
    /// few relayer submissions as possible.
    ///
    /// One balance snapshot plans everything ([`plan_jobs`]); every event's
    /// merges and convert tiers ride a single relayer submission when they
    /// fit, followed by exactly one settle wait, then one balance-read-sized
    /// wrap submission. The wrap cannot ride the batch: the relayer's
    /// pre-submission simulation evaluates each call against pre-batch
    /// state, where the proceeds don't exist yet. A failed submission (other
    /// than quota exhaustion) re-reads balances and rebuilds, absorbing
    /// mid-flight balance changes.
    pub async fn process_jobs<S: Signer + Sync>(
        jobs: &[&ConvertJob],
        signer: &S,
        relayer: &RelayerClient,
        rpc_url: &str,
        wallet: Address,
        delays: ConvertDelays,
    ) -> Result<String, Error> {
        /// Re-plans after a failed submission round (fresh balance read each
        /// time).
        const REBUILD_ATTEMPTS: usize = 2;

        let ConvertDelays {
            settle,
            wallet_busy_max_retries,
            single_leg_min_qty_raw,
            max_calls_per_submission,
            max_gas_per_submission,
            ..
        } = delays;

        let mut last_err: Option<Error> = None;
        for attempt in 0..=REBUILD_ATTEMPTS {
            if attempt > 0 {
                // A failed round may have landed earlier chunks that haven't
                // settled yet; re-reading too soon would re-plan (and
                // re-submit) their calls, which would then revert on-chain
                // against the already-burned balances.
                tokio::time::sleep(settle).await;
            }

            let outcome: Result<String, Error> = async {
                let (plans, snapshot) =
                    plan_jobs(jobs, rpc_url, wallet, single_leg_min_qty_raw).await?;
                let planned = plan_calls(&plans)?;
                if planned.is_empty() {
                    // USDC.e already sitting in the wallet still gets wrapped.
                    if snapshot.balance > U256::ZERO {
                        wrap_best_effort(signer, relayer, rpc_url, wallet, &delays, "leftover")
                            .await;
                        return Ok(format!(
                            "no-op: wrapped leftover {} USDC.e",
                            fmt_usdc(snapshot.balance)
                        ));
                    }
                    return Ok("no-op: nothing to merge/convert/wrap".into());
                }

                let merges: usize = plans
                    .iter()
                    .map(|p| {
                        p.merges.len()
                            + p.tiers.iter().map(|t| t.post_merges.len()).sum::<usize>()
                    })
                    .sum();
                let converts: usize = plans.iter().map(|p| p.tiers.len()).sum();
                let proceeds = plans.iter().fold(U256::ZERO, |acc, p| acc + p.proceeds);
                let gas_estimate: u64 = planned.iter().map(|p| p.gas).sum();
                let ranges =
                    gas_chunks(&planned, max_calls_per_submission, max_gas_per_submission);
                let n_chunks = ranges.len();
                tracing::info!(
                    events = jobs.len(),
                    merges,
                    converts,
                    proceeds = %fmt_usdc(proceeds),
                    gas_estimate,
                    chunks = n_chunks,
                    attempt,
                    "convert cycle planned"
                );

                let calls: Vec<DepositWalletCall> =
                    planned.into_iter().map(|p| p.call).collect();
                let mut tx_id = String::new();
                for (i, range) in ranges.into_iter().enumerate() {
                    let label = format!("cycle chunk {}/{n_chunks}", i + 1);
                    tx_id = submit_and_settle_with_busy_retry(
                        signer,
                        relayer,
                        wallet,
                        &calls[range],
                        &label,
                        settle,
                        wallet_busy_max_retries,
                    )
                    .await?;
                }

                // Wrap the freed USDC.e in its own submission, sized by a
                // fresh balance read (the last chunk's settle wait has
                // elapsed, so the read sees the proceeds plus any
                // pre-existing leftover).
                wrap_best_effort(signer, relayer, rpc_url, wallet, &delays, "post-batch").await;

                Ok(format!(
                    "events={} merges={merges} converts={converts} proceeds={} chunks={n_chunks} tx={tx_id}",
                    jobs.len(),
                    fmt_usdc(proceeds),
                ))
            }
            .await;

            match outcome {
                Ok(detail) => return Ok(detail),
                // The caller sleeps out the quota reset; a salvage wrap
                // submission would just burn another rejected request
                // against the same quota.
                Err(e @ Error::RelayerQuotaExhausted { .. }) => return Err(e),
                Err(e) => {
                    tracing::warn!(error = %e, attempt, "convert round failed; re-reading and rebuilding");
                    last_err = Some(e);
                }
            }
        }

        // Every round failed. Salvage: wrap whatever USDC.e the chunks that
        // did land freed, so it isn't stranded until the next cycle.
        wrap_best_effort(signer, relayer, rpc_url, wallet, &delays, "salvage").await;

        Err(last_err.unwrap_or_else(|| Error::InvalidData("convert cycle failed".into())))
    }

    /// Best-effort wrap of whatever USDC.e the wallet holds. A failure is
    /// logged, never fatal: the merges/converts that freed the cash already
    /// landed on-chain, and unwrapped USDC.e is picked up by the next
    /// cycle's leftover wrap.
    async fn wrap_best_effort<S: Signer + Sync>(
        signer: &S,
        relayer: &RelayerClient,
        rpc_url: &str,
        wallet: Address,
        delays: &ConvertDelays,
        context: &str,
    ) {
        if let Err(e) = wrap_with_busy_retry(
            signer,
            relayer,
            rpc_url,
            wallet,
            delays.wallet_busy_max_retries,
            delays.settle,
        )
        .await
        {
            tracing::warn!(error = %e, "{context} wrap failed");
        }
    }

    /// Single-event wrapper around [`process_jobs`].
    pub async fn process_job<S: Signer + Sync>(
        job: &ConvertJob,
        signer: &S,
        relayer: &RelayerClient,
        rpc_url: &str,
        wallet: Address,
        delays: ConvertDelays,
    ) -> Result<String, Error> {
        process_jobs(&[job], signer, relayer, rpc_url, wallet, delays).await
    }

    /// Submit a batch of YES+NO merges and wait for settlement.
    pub async fn process_merge<S: Signer + Sync>(
        merges: &[(B256, U256)],
        signer: &S,
        relayer: &RelayerClient,
        wallet: Address,
    ) -> Result<String, Error> {
        let calls = super::merge_calls(merges);

        let resp = relayer
            .submit_deposit_wallet_batch(signer, wallet, POLYGON, &calls)
            .await?;

        Ok(resp.transaction_id)
    }

    /// Submit a convert of NO positions and wait for settlement, returning
    /// the transaction id. Wrapping the freed USDC.e is left to the caller
    /// (via [`wrap_with_busy_retry`]), mirroring [`process_merge`].
    pub async fn process_convert<S: Signer + Sync>(
        question_ids: &[B256],
        amount_raw: U256,
        signer: &S,
        relayer: &RelayerClient,
        wallet: Address,
        settle: Duration,
    ) -> Result<String, Error> {
        let convert_data = build_convert_calldata(question_ids, amount_raw)?;
        let tx_id = submit_and_settle(
            signer,
            relayer,
            wallet,
            &[DepositWalletCall {
                target: NEG_RISK_COLLATERAL_ADAPTER,
                data: convert_data,
            }],
            "convert",
            settle,
        )
        .await?;

        Ok(tx_id)
    }

    /// Wrap the wallet's whole USDC.e balance into pUSD, including an
    /// unlimited approve when the onramp allowance falls short.
    pub async fn wrap_usdc_e<S: Signer + Sync>(
        signer: &S,
        relayer: &RelayerClient,
        rpc_url: &str,
        wallet: Address,
    ) -> Result<(), Error> {
        let snapshot = read_wrap_snapshot(rpc_url, wallet).await?;

        if snapshot.balance == U256::ZERO {
            tracing::info!("no USDC.e to wrap");
            return Ok(());
        }

        let include_approve = snapshot.allowance < snapshot.balance;
        if include_approve {
            tracing::info!(balance = %snapshot.balance, "including USDC approve in wrap batch");
        }
        tracing::info!(balance = %snapshot.balance, "wrapping USDC.e to pUSD");
        let calls = wrap_calls(wallet, snapshot.balance, include_approve);

        let resp = relayer
            .submit_deposit_wallet_batch(signer, wallet, POLYGON, &calls)
            .await?;
        tracing::info!(tx_id = %resp.transaction_id, "wrap submitted");

        Ok(())
    }

    /// Wrap USDC.e → pUSD after a merge/convert, retrying while the wallet
    /// is busy.
    ///
    /// The merge/convert just submitted can still be settling when the wrap
    /// goes out, and the relayer rejects the concurrent action with "wallet
    /// busy". The condition clears once the prior action lands on-chain, so
    /// wait `retry_wait` and try again, up to `max_retries` times.
    pub async fn wrap_with_busy_retry<S: Signer + Sync>(
        signer: &S,
        relayer: &RelayerClient,
        rpc_url: &str,
        wallet: Address,
        max_retries: u32,
        retry_wait: Duration,
    ) -> Result<(), Error> {
        let mut attempt = 0;
        loop {
            match wrap_usdc_e(signer, relayer, rpc_url, wallet).await {
                Ok(()) => return Ok(()),
                Err(e) if e.is_wallet_busy() && attempt < max_retries => {
                    attempt += 1;
                    tracing::warn!(
                        attempt,
                        max_retries,
                        wait_secs = retry_wait.as_secs(),
                        "wrap deferred: wallet busy, waiting then retrying"
                    );
                    tokio::time::sleep(retry_wait).await;
                }
                Err(e) => return Err(e),
            }
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        fn job(slug: &str) -> ConvertJob {
            ConvertJob {
                slug: slug.into(),
                legs: Vec::new(),
                amount_raw: U256::ZERO,
                attempts: 0,
                queued_at: Instant::now(),
            }
        }

        /// Test leg: question id tagged with `n`, NO token id `2000 + n`,
        /// YES token id `1000 + n` when `yes`, condition id tagged with `n`
        /// when `cond`.
        fn leg(n: u8, yes: bool, cond: bool) -> ConvertLeg {
            let mut qid = [0_u8; 32];
            qid[0] = n;
            let mut cid = [0_u8; 32];
            cid[1] = n;
            ConvertLeg {
                question_id: B256::from(qid),
                condition_id: cond.then(|| B256::from(cid)),
                yes_token_id: yes.then(|| U256::from(1000_u64 + u64::from(n))),
                no_token_id: U256::from(2000_u64 + u64::from(n)),
            }
        }

        #[test]
        fn batch_ids_layout_no_then_yes_when_present() {
            let legs = [leg(1, true, true), leg(2, false, true), leg(3, true, false)];
            assert_eq!(
                batch_token_ids(&legs),
                vec![
                    U256::from(2001_u64),
                    U256::from(1001_u64),
                    U256::from(2002_u64),
                    U256::from(2003_u64),
                    U256::from(1003_u64),
                ]
            );
            assert_eq!(token_count(&legs), 5);
        }

        #[test]
        fn unpack_round_trips_layout() {
            let legs = [leg(1, true, true), leg(2, false, true), leg(3, true, false)];
            let balances = [
                U256::from(10_u64),
                U256::from(11_u64),
                U256::from(20_u64),
                U256::from(30_u64),
                U256::from(31_u64),
            ];
            let pairs = unpack_balances(&legs, &balances).unwrap();
            assert_eq!(
                pairs,
                vec![
                    (U256::from(10_u64), U256::from(11_u64)),
                    (U256::from(20_u64), U256::ZERO),
                    (U256::from(30_u64), U256::from(31_u64)),
                ]
            );
        }

        #[test]
        fn unpack_short_result_errors() {
            let legs = [leg(1, true, true), leg(2, false, true)];
            let balances = [U256::from(10_u64), U256::from(11_u64)];
            assert!(unpack_balances(&legs, &balances).is_err());
        }

        #[test]
        fn unpack_long_result_errors() {
            let legs = [leg(1, false, true)];
            let balances = [U256::from(10_u64), U256::from(11_u64)];
            assert!(unpack_balances(&legs, &balances).is_err());
        }

        #[test]
        fn unpack_multi_round_trips_jobs() {
            let mut a = job("a");
            a.legs = vec![leg(1, true, true), leg(2, false, true)]; // 3 ids
            let mut b = job("b");
            b.legs = vec![leg(3, true, false)]; // 2 ids
            let balances = [
                U256::from(10_u64),
                U256::from(11_u64),
                U256::from(20_u64),
                U256::from(30_u64),
                U256::from(31_u64),
            ];
            let per_job = unpack_multi(&[&a, &b], &balances).unwrap();
            assert_eq!(
                per_job,
                vec![
                    vec![
                        (U256::from(10_u64), U256::from(11_u64)),
                        (U256::from(20_u64), U256::ZERO),
                    ],
                    vec![(U256::from(30_u64), U256::from(31_u64))],
                ]
            );
        }

        #[test]
        fn unpack_multi_short_and_long_error() {
            let mut a = job("a");
            a.legs = vec![leg(1, true, true)]; // 2 ids
            let short = [U256::from(10_u64)];
            assert!(unpack_multi(&[&a], &short).is_err());
            let long = [U256::from(10_u64), U256::from(11_u64), U256::from(12_u64)];
            assert!(unpack_multi(&[&a], &long).is_err());
        }

        #[test]
        fn dedup_by_slug_first_wins() {
            let batch = [job("a"), job("b"), job("a")];
            let uniques = dedup_by_slug(&batch);
            assert_eq!(uniques.len(), 2);
            assert_eq!(uniques[0].slug, "a");
            assert_eq!(uniques[1].slug, "b");
        }

        #[test]
        fn fill_residual_math() {
            let base = Instant::now();
            let delay = Duration::from_secs(3);

            assert_eq!(fill_residual(&[], base, delay), Duration::ZERO);

            let mut aged = job("a");
            aged.queued_at = base;
            // 5s after queueing the delay is fully served.
            assert_eq!(
                fill_residual(
                    std::slice::from_ref(&aged),
                    base + Duration::from_secs(5),
                    delay
                ),
                Duration::ZERO
            );

            let mut young = job("b");
            young.queued_at = base + Duration::from_secs(4);
            // 1s after queueing, 2s of the delay remain; the max across the
            // batch (aged needs 0) is the young job's residual.
            assert_eq!(
                fill_residual(&[aged, young], base + Duration::from_secs(5), delay),
                Duration::from_secs(2)
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use alloy::primitives::keccak256;

    use super::*;

    #[test]
    fn market_id_zeros_last_byte() {
        let qid = "aa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55403"
            .parse::<B256>()
            .unwrap();
        let mid = market_id_from_question_id(&qid);
        assert_eq!(mid.0[31], 0);
        assert_eq!(mid.0[..31], qid.0[..31]);
    }

    #[test]
    fn market_id_already_zero_is_noop() {
        let qid = "aa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55400"
            .parse::<B256>()
            .unwrap();
        let mid = market_id_from_question_id(&qid);
        assert_eq!(mid, qid);
    }

    #[test]
    fn index_set_single_question() {
        let qid = "aa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55403"
            .parse::<B256>()
            .unwrap();
        let bits = index_set(&[qid]);
        assert_eq!(bits, U256::from(1_u64 << 3));
    }

    #[test]
    fn index_set_multiple_questions() {
        let q0 = "aa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55400"
            .parse::<B256>()
            .unwrap();
        let q1 = "aa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55401"
            .parse::<B256>()
            .unwrap();
        let q5 = "aa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55405"
            .parse::<B256>()
            .unwrap();
        let bits = index_set(&[q0, q1, q5]);
        // bit 0 | bit 1 | bit 5 = 1 + 2 + 32 = 35
        assert_eq!(bits, U256::from(35_u64));
    }

    #[test]
    fn index_set_empty_is_zero() {
        assert_eq!(index_set(&[]), U256::ZERO);
    }

    #[test]
    fn build_calldata_empty_question_ids_errors() {
        assert!(build_convert_calldata(&[], U256::from(5_000_000_u64)).is_err());
    }

    #[test]
    fn build_calldata_produces_valid_encoding() {
        let q0 = "aa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55400"
            .parse::<B256>()
            .unwrap();
        let q1 = "aa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55401"
            .parse::<B256>()
            .unwrap();
        let data = build_convert_calldata(&[q0, q1], U256::from(5_000_000_u64)).unwrap();
        // 4-byte selector + 3 * 32-byte args = 100 bytes
        assert_eq!(data.len(), 100);
        assert_eq!(
            &data[..4],
            &keccak256(b"convertPositions(bytes32,uint256,uint256)")[..4]
        );
    }

    #[test]
    fn merge_calldata_uses_ctf_mirror_overload() {
        // The collateral adapter's legacy 2-arg mergePositions reverts; the
        // working entrypoint is the CTF-mirror form with pUSD collateral.
        let cid = B256::repeat_byte(0x11);
        let data = build_merge_calldata(&cid, U256::from(1_u64));
        assert_eq!(data.len(), 4 + 8 * 32);
        assert_eq!(
            &data[..4],
            &keccak256(b"mergePositions(address,bytes32,bytes32,uint256[],uint256)")[..4]
        );
        // Byte-identical to the explicit CTF-mirror builder with pUSD collateral.
        assert_eq!(
            data,
            build_merge_calldata_ctf(COLLATERAL, &cid, U256::from(1_u64))
        );

        let calls = merge_calls(&[(cid, U256::from(1_u64))]);
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].target, NEG_RISK_COLLATERAL_ADAPTER);
        assert_eq!(calls[0].data, data);
    }

    #[test]
    fn split_calldata_uses_ctf_mirror_overload() {
        // Split takes the exact symmetric CTF-mirror shape of the verified
        // merge, through the same collateral adapter.
        let cid = B256::repeat_byte(0x22);
        let data = build_split_calldata(&cid, U256::from(5_000_000_u64));
        assert_eq!(data.len(), 4 + 8 * 32);
        assert_eq!(
            &data[..4],
            &keccak256(b"splitPosition(address,bytes32,bytes32,uint256[],uint256)")[..4]
        );
        assert_eq!(
            data,
            build_split_calldata_ctf(COLLATERAL, &cid, U256::from(5_000_000_u64))
        );

        let calls = split_calls(&[(cid, U256::from(5_000_000_u64))]);
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].target, NEG_RISK_COLLATERAL_ADAPTER);
        assert_eq!(calls[0].data, data);
    }

    #[test]
    fn ctf_split_and_merge_calldata_layout() {
        let cid = B256::repeat_byte(0x33);
        let collateral = USDC_E;
        let split = build_split_calldata_ctf(collateral, &cid, U256::from(7_u64));
        // selector(4) + address + parent + conditionId + array offset +
        // amount (5 words) + array len + 2 elements (3 words) = 4 + 8*32.
        assert_eq!(split.len(), 4 + 8 * 32);
        assert_eq!(
            &split[..4],
            &keccak256(b"splitPosition(address,bytes32,bytes32,uint256[],uint256)")[..4]
        );

        let merge = build_merge_calldata_ctf(collateral, &cid, U256::from(7_u64));
        assert_eq!(merge.len(), 4 + 8 * 32);
        assert_eq!(
            &merge[..4],
            &keccak256(b"mergePositions(address,bytes32,bytes32,uint256[],uint256)")[..4]
        );
        // Same arguments, different selector.
        assert_eq!(&split[4..], &merge[4..]);
    }

    #[test]
    fn redeem_calldata_uses_ctf_mirror_overload() {
        let cid = "aa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55403"
            .parse::<B256>()
            .unwrap();
        // Only YES held → the single index set [1]; CTF-mirror redeem.
        let data = build_redeem_calldata(&cid, U256::from(523_000_000_u64), U256::ZERO);
        // selector(4) + collateral + parent + conditionId + offset + len + 1 elem = 4 + 6*32
        assert_eq!(data.len(), 4 + 6 * 32);
        assert_eq!(
            &data[..4],
            &keccak256(b"redeemPositions(address,bytes32,bytes32,uint256[])")[..4]
        );
        // Held-side inclusion, not amounts: YES>0,NO=0 ⇒ index sets [1].
        assert_eq!(
            data,
            build_redeem_calldata_ctf(COLLATERAL, &cid, &[U256::from(1_u64)])
        );

        // Both sides held ⇒ both index sets, against the collateral adapter.
        let calls = redeem_calls(&[(cid, U256::from(1_u64), U256::from(2_u64))]);
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].target, NEG_RISK_COLLATERAL_ADAPTER);
        assert_eq!(
            calls[0].data,
            build_redeem_calldata_ctf(COLLATERAL, &cid, &[U256::from(1_u64), U256::from(2_u64)])
        );
    }

    #[test]
    fn ctf_redeem_calldata_selector_and_layout() {
        let cid = B256::repeat_byte(0x44);
        let data = build_redeem_calldata_ctf(USDC_E, &cid, &[U256::from(1_u64), U256::from(2_u64)]);
        // selector(4) + collateral + parent + conditionId + array offset +
        // len + 2 elems = 4 + 7*32.
        assert_eq!(data.len(), 4 + 7 * 32);
        assert_eq!(
            &data[..4],
            &keccak256(b"redeemPositions(address,bytes32,bytes32,uint256[])")[..4]
        );
    }

    #[test]
    fn convert_legs_parses_and_skips() {
        let markets = [
            MarketIds {
                question_id: Some(
                    "0xaa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55401",
                ),
                condition_id: Some(
                    "bb0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55401",
                ),
                yes_token_id: Some("1001"),
                no_token_id: "2001",
            },
            // Missing question id → skipped.
            MarketIds {
                question_id: None,
                condition_id: None,
                yes_token_id: None,
                no_token_id: "2002",
            },
            // Garbage NO token id → skipped.
            MarketIds {
                question_id: Some(
                    "0xaa0edfa656a0e70bf8c63f09438cd70979fef8e31fcc62d80840b5a375a55403",
                ),
                condition_id: None,
                yes_token_id: None,
                no_token_id: "not-a-number",
            },
        ];
        let legs = convert_legs(markets);
        assert_eq!(legs.len(), 1);
        assert_eq!(legs[0].no_token_id, U256::from(2001_u64));
        assert_eq!(legs[0].yes_token_id, Some(U256::from(1001_u64)));
        assert!(legs[0].condition_id.is_some());
    }

    #[test]
    fn fmt_usdc_renders_six_decimals() {
        assert_eq!(fmt_usdc(U256::from(12_345_678_u64)), "12.345678");
        assert_eq!(fmt_usdc(U256::ZERO), "0.000000");
        assert_eq!(fmt_usdc(U256::from(42_u64)), "0.000042");
    }

    /// Test holding: question id with position index `n` (last byte, so
    /// index-set bits stay distinct), condition id tagged with `n` when
    /// `cond`.
    fn holding(n: u8, cond: bool, remaining: u64) -> NoHolding {
        let mut qid = [0_u8; 32];
        qid[31] = n;
        let mut cid = [0_u8; 32];
        cid[1] = n;
        NoHolding {
            question_id: B256::from(qid),
            condition_id: cond.then(|| B256::from(cid)),
            remaining_no: U256::from(remaining),
        }
    }

    /// Test leg: question id tagged with `n`, NO token id `2000 + n`, YES
    /// token id `1000 + n` when `yes`, condition id tagged with `n` when
    /// `cond`.
    fn leg(n: u8, yes: bool, cond: bool) -> ConvertLeg {
        let mut qid = [0_u8; 32];
        qid[0] = n;
        let mut cid = [0_u8; 32];
        cid[1] = n;
        ConvertLeg {
            question_id: B256::from(qid),
            condition_id: cond.then(|| B256::from(cid)),
            yes_token_id: yes.then(|| U256::from(1000_u64 + u64::from(n))),
            no_token_id: U256::from(2000_u64 + u64::from(n)),
        }
    }

    #[test]
    fn classify_merges_pair_and_nets_remainder() {
        // Leg 1: YES 7 / NO 5 → merge 5, nothing left over.
        // Leg 2: YES 3 / NO 9 → merge 3, 6 NO left over.
        let legs = [leg(1, true, true), leg(2, true, true)];
        let balances = [
            (U256::from(5_u64), U256::from(7_u64)),
            (U256::from(9_u64), U256::from(3_u64)),
        ];
        let (merges, holdings) = classify_event(&legs, &balances);
        assert_eq!(
            merges,
            vec![
                (legs[0].condition_id.unwrap(), U256::from(5_u64)),
                (legs[1].condition_id.unwrap(), U256::from(3_u64)),
            ]
        );
        assert_eq!(
            holdings,
            vec![NoHolding {
                question_id: legs[1].question_id,
                condition_id: legs[1].condition_id,
                remaining_no: U256::from(6_u64),
            }]
        );
    }

    #[test]
    fn classify_missing_condition_id_skips_merge() {
        let legs = [leg(1, true, false)];
        let balances = [(U256::from(5_u64), U256::from(5_u64))];
        let (merges, holdings) = classify_event(&legs, &balances);
        // The pair can't merge without a condition id, and the NO side is
        // fully offset by YES, so nothing remains to convert either.
        assert!(merges.is_empty());
        assert!(holdings.is_empty());
    }

    #[test]
    fn classify_keeps_leg_order() {
        let legs = [leg(1, false, true), leg(2, false, true)];
        let balances = [
            (U256::from(6_u64), U256::ZERO),
            (U256::from(4_u64), U256::ZERO),
        ];
        let (merges, holdings) = classify_event(&legs, &balances);
        assert!(merges.is_empty());
        assert_eq!(holdings.len(), 2);
        assert_eq!(holdings[0].question_id, legs[0].question_id);
        assert_eq!(holdings[0].remaining_no, U256::from(6_u64));
        assert_eq!(holdings[1].question_id, legs[1].question_id);
        assert_eq!(holdings[1].remaining_no, U256::from(4_u64));
    }

    #[test]
    fn classify_nothing_held_is_empty() {
        let legs = [leg(1, true, true), leg(2, false, true)];
        let balances = [(U256::ZERO, U256::ZERO), (U256::ZERO, U256::ZERO)];
        let (merges, holdings) = classify_event(&legs, &balances);
        assert!(merges.is_empty());
        assert!(holdings.is_empty());
    }

    #[test]
    fn tiers_uniform_levels_single_tier() {
        let hs = [
            holding(1, true, 7),
            holding(2, true, 7),
            holding(3, true, 7),
        ];
        let tiers = plan_tiers(&hs, U256::ZERO, 20);
        assert_eq!(tiers.len(), 1);
        assert_eq!(tiers[0].amount, U256::from(7_u64));
        assert_eq!(
            tiers[0].question_ids,
            vec![hs[0].question_id, hs[1].question_id, hs[2].question_id]
        );
        assert!(tiers[0].post_merges.is_empty());
    }

    #[test]
    fn tiers_uneven_levels_decompose() {
        // [3,5,5,9] → convert 3 across all 4, then 2 across the ≥5 legs,
        // then the lone 9-leg's last 4.
        let hs = [
            holding(1, true, 3),
            holding(2, true, 5),
            holding(3, true, 5),
            holding(4, true, 9),
        ];
        let tiers = plan_tiers(&hs, U256::ZERO, 20);
        assert_eq!(tiers.len(), 3);
        assert_eq!(tiers[0].amount, U256::from(3_u64));
        assert_eq!(tiers[0].question_ids.len(), 4);
        assert_eq!(tiers[1].amount, U256::from(2_u64));
        assert_eq!(
            tiers[1].question_ids,
            vec![hs[1].question_id, hs[2].question_id, hs[3].question_id]
        );
        assert_eq!(tiers[2].amount, U256::from(4_u64));
        assert_eq!(tiers[2].question_ids, vec![hs[3].question_id]);
        assert!(tiers.iter().all(|t| t.post_merges.is_empty()));
    }

    #[test]
    fn tiers_empty_holdings_no_tiers() {
        assert!(plan_tiers(&[], U256::from(100_u64), 20).is_empty());
    }

    #[test]
    fn tiers_single_leg_dust_floor() {
        // Below the floor: skipped. At the floor: converted (strict <).
        let hs = [holding(1, true, 5)];
        assert!(plan_tiers(&hs, U256::from(6_u64), 20).is_empty());
        let tiers = plan_tiers(&hs, U256::from(5_u64), 20);
        assert_eq!(tiers.len(), 1);
        assert_eq!(tiers[0].amount, U256::from(5_u64));
    }

    #[test]
    fn tiers_final_single_leg_dropped_earlier_kept() {
        // Floor 5 drops only the final lone-leg tier (amount 4); the earlier
        // multi-leg tiers convert regardless of amount.
        let hs = [
            holding(1, true, 3),
            holding(2, true, 5),
            holding(3, true, 5),
            holding(4, true, 9),
        ];
        let tiers = plan_tiers(&hs, U256::from(5_u64), 20);
        assert_eq!(tiers.len(), 2);
        assert_eq!(tiers[0].amount, U256::from(3_u64));
        assert_eq!(tiers[1].amount, U256::from(2_u64));
    }

    #[test]
    fn tiers_truncation_emits_post_merges() {
        // 5 uniform legs, cap 3: convert the first 3; the truncated-out legs
        // get compensating merges — except the cid-less one, which can't
        // merge.
        let hs = [
            holding(1, true, 7),
            holding(2, true, 7),
            holding(3, true, 7),
            holding(4, true, 7),
            holding(5, false, 7),
        ];
        let tiers = plan_tiers(&hs, U256::ZERO, 3);
        assert_eq!(tiers.len(), 1);
        assert_eq!(tiers[0].amount, U256::from(7_u64));
        assert_eq!(
            tiers[0].question_ids,
            vec![hs[0].question_id, hs[1].question_id, hs[2].question_id]
        );
        assert_eq!(
            tiers[0].post_merges,
            vec![(hs[3].condition_id.unwrap(), U256::from(7_u64))]
        );
    }

    #[test]
    fn tiers_multi_tier_truncation_tracks_running_balances() {
        // [5,5,5,5,8], cap 3: tier 1 converts 5 on the first three and
        // post-merges the truncated two; tier 2 is the deep leg's remaining
        // 3 (8 − 5 burned via its tier-1 post-merge).
        let hs = [
            holding(1, true, 5),
            holding(2, true, 5),
            holding(3, true, 5),
            holding(4, true, 5),
            holding(5, true, 8),
        ];
        let tiers = plan_tiers(&hs, U256::ZERO, 3);
        assert_eq!(tiers.len(), 2);
        assert_eq!(tiers[0].amount, U256::from(5_u64));
        assert_eq!(tiers[0].question_ids.len(), 3);
        assert_eq!(
            tiers[0].post_merges,
            vec![
                (hs[3].condition_id.unwrap(), U256::from(5_u64)),
                (hs[4].condition_id.unwrap(), U256::from(5_u64)),
            ]
        );
        assert_eq!(tiers[1].amount, U256::from(3_u64));
        assert_eq!(tiers[1].question_ids, vec![hs[4].question_id]);
        assert!(tiers[1].post_merges.is_empty());
    }

    #[test]
    fn plan_event_sums_exact_proceeds() {
        // merges 5; tiers (k4,a3) → 9, (k3,a2) → 4, (k1,a4) → 0. Total 18.
        let hs = [
            holding(1, true, 3),
            holding(2, true, 5),
            holding(3, true, 5),
            holding(4, true, 9),
        ];
        let tiers = plan_tiers(&hs, U256::ZERO, 20);
        let merges = vec![(hs[0].condition_id.unwrap(), U256::from(5_u64))];
        let plan = plan_event(merges, tiers, 4);
        assert_eq!(plan.proceeds, U256::from(18_u64));
        assert_eq!(plan.n_legs, 4);
    }

    #[test]
    fn plan_event_truncation_preserves_proceeds() {
        // 5 legs @7 capped at 3: (3−1)·7 from the convert + 7+7 from the
        // post-merges == the untruncated (5−1)·7.
        let hs = [
            holding(1, true, 7),
            holding(2, true, 7),
            holding(3, true, 7),
            holding(4, true, 7),
            holding(5, true, 7),
        ];
        let tiers = plan_tiers(&hs, U256::ZERO, 3);
        let plan = plan_event(Vec::new(), tiers, 5);
        assert_eq!(plan.proceeds, U256::from(28_u64));
    }

    #[test]
    fn plan_calls_orders_merges_converts_post_merges() {
        let hs = [
            holding(1, true, 7),
            holding(2, true, 7),
            holding(3, true, 7),
            holding(4, true, 7),
        ];
        let tiers = plan_tiers(&hs, U256::ZERO, 3);
        let merges = vec![(hs[0].condition_id.unwrap(), U256::from(5_u64))];
        let plan = plan_event(merges, tiers, 4);
        let calls = plan_calls(&[plan]).unwrap();

        // merge, convert, post-merge — the wrap is NOT planned here (it goes
        // out post-batch by balance read; an in-batch proceeds-sized wrap is
        // rejected by the relayer's simulation).
        assert_eq!(calls.len(), 3);
        assert_eq!(calls[0].call.target, NEG_RISK_COLLATERAL_ADAPTER);
        assert_eq!(
            calls[0].call.data[..4],
            ICtfOps::mergePositionsCall::SELECTOR
        );
        assert_eq!(calls[0].gas, MERGE_GAS);
        assert_eq!(calls[1].call.target, NEG_RISK_COLLATERAL_ADAPTER);
        assert_eq!(
            calls[1].call.data[..4],
            INegRiskAdapterOps::convertPositionsCall::SELECTOR
        );
        assert_eq!(calls[1].gas, convert_gas(4));
        assert_eq!(calls[2].call.target, NEG_RISK_COLLATERAL_ADAPTER);
        assert_eq!(
            calls[2].call.data[..4],
            ICtfOps::mergePositionsCall::SELECTOR
        );
        assert_eq!(calls[2].gas, MERGE_GAS);
    }

    #[test]
    fn plan_calls_empty_when_nothing_to_do() {
        assert!(plan_calls(&[]).unwrap().is_empty());
        let empty_plan = EventPlan::default();
        assert!(plan_calls(&[empty_plan]).unwrap().is_empty());
    }

    #[test]
    fn plan_calls_large_plan_emits_every_call() {
        // 25 merge-only legs → 25 calls; the 20-call submission cap alone
        // splits them into 2 sequential submissions (merges are cheap, so
        // the 8M gas budget fits 20 of them).
        let merges: Vec<(B256, U256)> = (1..=25_u8)
            .map(|n| {
                let mut cid = [0_u8; 32];
                cid[1] = n;
                (B256::from(cid), U256::from(1_000_000_u64))
            })
            .collect();
        let plan = plan_event(merges, Vec::new(), 25);
        let calls = plan_calls(&[plan]).unwrap();
        assert_eq!(calls.len(), 25);
        let ranges = gas_chunks(&calls, 20, 8_000_000);
        assert_eq!(ranges, vec![0..20, 20..25]);
    }

    /// Shorthand for a [`PlannedCall`] with the given gas weight (calldata
    /// is irrelevant to chunking).
    fn pc(gas: u64) -> PlannedCall {
        PlannedCall {
            call: DepositWalletCall {
                target: NEG_RISK_COLLATERAL_ADAPTER,
                data: Vec::new(),
            },
            gas,
        }
    }

    #[test]
    fn gas_chunks_empty_and_single_chunk() {
        assert!(gas_chunks(&[], 20, 8_000_000).is_empty());
        let planned = [pc(1_000_000), pc(2_000_000), pc(3_000_000)];
        assert_eq!(gas_chunks(&planned, 20, 8_000_000), vec![0..3]);
    }

    #[test]
    fn gas_chunks_splits_on_gas_budget() {
        // The shape that broke live: one cheap merge + six ~7M converts must
        // NOT share submissions under an 8M budget.
        let planned = [
            pc(400_000),
            pc(7_000_000),
            pc(7_000_000),
            pc(7_000_000),
            pc(7_000_000),
            pc(7_000_000),
            pc(7_000_000),
        ];
        assert_eq!(
            gas_chunks(&planned, 20, 8_000_000),
            vec![0..2, 2..3, 3..4, 4..5, 5..6, 6..7]
        );
    }

    #[test]
    fn gas_chunks_oversize_call_gets_own_chunk() {
        // A single call over the budget is atomic and still submits alone,
        // without starving its neighbours.
        let planned = [pc(400_000), pc(12_000_000), pc(400_000)];
        assert_eq!(gas_chunks(&planned, 20, 8_000_000), vec![0..1, 1..2, 2..3]);
    }

    #[test]
    fn gas_chunks_count_cap_still_applies() {
        let planned = [pc(1), pc(1), pc(1), pc(1), pc(1)];
        assert_eq!(gas_chunks(&planned, 2, 8_000_000), vec![0..2, 2..4, 4..5]);
        // Degenerate cap clamps to 1.
        assert_eq!(gas_chunks(&planned[..2], 0, 8_000_000), vec![0..1, 1..2]);
    }

    #[test]
    fn wrap_calls_shapes() {
        let wallet = NEG_RISK_COLLATERAL_ADAPTER; // any address works for the shape test
        let no_approve = wrap_calls(wallet, U256::from(5_u64), false);
        assert_eq!(no_approve.len(), 1);
        assert_eq!(no_approve[0].target, COLLATERAL_ONRAMP);
        assert_eq!(
            &no_approve[0].data[..4],
            &keccak256(b"wrap(address,address,uint256)")[..4]
        );

        let with_approve = wrap_calls(wallet, U256::from(5_u64), true);
        assert_eq!(with_approve.len(), 2);
        assert_eq!(with_approve[0].target, USDC_E);
        assert_eq!(
            &with_approve[0].data[..4],
            &keccak256(b"approve(address,uint256)")[..4]
        );
    }
}
